@ cdecl NVGSDK_AttachLogListener(ptr)
@ cdecl NVGSDK_Create(ptr ptr ptr)
@ cdecl NVGSDK_GetUILanguageAsync(ptr ptr ptr)
#@ cdecl NVGSDK_Highlights_CloseGroupAsync(ptr ptr ptr ptr)
#@ cdecl NVGSDK_Highlights_ConfigureAsync(ptr ptr ptr ptr)
#@ cdecl NVGSDK_Highlights_GetNumberOfHighlightsAsync(ptr ptr ptr ptr)
#@ cdecl NVGSDK_Highlights_GetUserSettingsAsync(ptr ptr ptr)
#@ cdecl NVGSDK_Highlights_OpenGroupAsync(ptr ptr ptr ptr)
#@ cdecl NVGSDK_Highlights_OpenSummaryAsync(ptr ptr ptr ptr)
#@ cdecl NVGSDK_Highlights_SetScreenshotHighlightAsync(ptr ptr ptr ptr)
#@ cdecl NVGSDK_Highlights_SetVideoHighlightAsync(ptr ptr ptr ptr)
@ cdecl NVGSDK_Poll(ptr)
@ cdecl NVGSDK_Release(ptr)
@ cdecl NVGSDK_RequestPermissionsAsync(ptr ptr ptr ptr)
@ cdecl NVGSDK_SetListenerLogLevel(long)
@ cdecl NVGSDK_SetLogLevel(long)
