# main Gitlab CI script

stages:
  - image
  - build
  - test
  - deploy

include:
  - local: "/tools/gitlab/image.yml"
  - local: "/tools/gitlab/build.yml"
  - local: "/tools/gitlab/test.yml"
  - local: "/tools/gitlab/release.yml"
